name: Notion Files Embedding

on:
  schedule:
    # 毎日午前6時に実行（UTC時間、日本時間だと15時）
    - cron: '0 6 * * *'
  workflow_dispatch:
    # 手動実行用
    inputs:
      page_id:
        description: '特定のページIDを指定（省略時は全ページ処理）'
        required: false
        default: ''

jobs:
  embed-files:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Python環境のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ワークスペース情報表示
        run: |
          pwd
          ls -la
          echo "Current directory: $(pwd)"

      - name: Notionページへのファイル埋め込み実行
        run: |
          echo "uploadformテーブルのファイルをNotionページに埋め込みます..."
          
          # ページIDが指定されていればそれを使用
          if [ -n "${{ github.event.inputs.page_id }}" ]; then
            echo "特定のページを処理: ${{ github.event.inputs.page_id }}"
            python main.py --page_id "${{ github.event.inputs.page_id }}" --embed
          else
            echo "uploadformテーブルの全ページを処理"
            python main.py --embed
          fi
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          UPLOADFORM_TABLEKEY: ${{ secrets.UPLOADFORM_TABLEKEY }}
          DATA_MANAGE_TABLEKEY: ${{ secrets.DATA_MANAGE_TABLEKEY }}
          UPLOADFORM_DB_ID: ${{ secrets.UPLOADFORM_DB_ID }}
