name: Notion Files Embedding

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    # 手動実行用（パラメータなし）

jobs:
  embed-files:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Python環境のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ワークスペース情報表示
        run: |
          pwd
          ls -la
          echo "Current directory: $(pwd)"

      - name: Notionページへのファイル埋め込み実行
        run: |
          echo "uploadformテーブルの全ページにファイルを埋め込みます..."
          python main.py --embed
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          UPLOADFORM_TABLEKEY: ${{ secrets.UPLOADFORM_TABLEKEY }}
          DATA_MANAGE_TABLEKEY: ${{ secrets.DATA_MANAGE_TABLEKEY }}
          UPLOADFORM_DB_ID: ${{ secrets.UPLOADFORM_DB_ID }}
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}
          GDRIVE_SHARE_EMAIL: ${{ secrets.GDRIVE_SHARE_EMAIL }}
