name: Notion Files Embedding

on:
  schedule:
    # 毎日午前6時に実行（UTC時間、日本時間だと15時）
    - cron: '0 6 * * *'
  workflow_dispatch:
    # 手動実行用
    inputs:
      database_id:
        description: '特定のデータベースIDを指定（省略時はデフォルト値を使用）'
        required: false
        default: ''
      page_id:
        description: '特定のページIDを指定（省略時は全ページ処理）'
        required: false
        default: ''

jobs:
  embed-files:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Python環境のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ワークスペース情報表示
        run: |
          pwd
          ls -la
          echo "Current directory: $(pwd)"

      - name: データベースIDの確認
        id: check-db-id
        run: |
          # 入力値またはシークレットからデータベースIDを設定
          INPUT_DB_ID="${{ github.event.inputs.database_id }}"
          SECRET_DB_ID="${{ secrets.DEFAULT_DATABASE_ID }}"
          
          # 入力値が設定されていればそれを使用、なければシークレットを使用
          if [ -n "$INPUT_DB_ID" ]; then
            echo "Using database ID from workflow input"
            echo "database_id=$INPUT_DB_ID" >> $GITHUB_OUTPUT
          elif [ -n "$SECRET_DB_ID" ]; then
            echo "Using database ID from repository secrets"
            echo "database_id=$SECRET_DB_ID" >> $GITHUB_OUTPUT
          else
            echo "ERROR: No database ID specified. Please provide --database_id parameter or set DEFAULT_DATABASE_ID secret."
            exit 1
          fi

      - name: Notionページへのファイル埋め込み実行
        run: |
          # 前のステップで検証済みのデータベースIDを使用
          DB_ID="${{ steps.check-db-id.outputs.database_id }}"
          echo "Using database ID: $DB_ID"
          
          # ページIDが指定されていればそれを使用
          if [ -n "${{ github.event.inputs.page_id }}" ]; then
            echo "Processing specific page: ${{ github.event.inputs.page_id }}"
            python main.py --database_id "$DB_ID" --page_id "${{ github.event.inputs.page_id }}" --embed
          else
            echo "Processing all pages in database"
            python main.py --database_id "$DB_ID" --embed
          fi
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          UPLOADFORM_TABLEKEY: ${{ secrets.UPLOADFORM_TABLEKEY }}
          DATA_MANAGE_TABLEKEY: ${{ secrets.DATA_MANAGE_TABLEKEY }}
