name: Notion File Manager

on:
  schedule:
    # 毎日午前3時に実行（UTC時間）- 日本時間だと正午頃
    - cron: '0 3 * * *'
  # 手動実行も可能に
  workflow_dispatch:

jobs:
  sync-notion-files:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Pythonのセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 一時ディレクトリの作成
        run: mkdir -p /tmp/notion_temp

      - name: Notionファイル管理スクリプトの実行
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATA_MANAGE_TABLEKEY: ${{ secrets.DATA_MANAGE_TABLEKEY }}
          UPLOADFORM_TABLEKEY: ${{ secrets.UPLOADFORM_TABLEKEY }}
          TEMP_DIR: /tmp/notion_temp
        run: |
          python notionManage/notion_file_manager.py

      - name: 一時ファイルのクリーンアップ
        run: |
          rm -rf /tmp/notion_temp
          echo "一時ファイルを削除しました"
